version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - "../volumes/pgdata:/var/lib/postgresql/data"
  suapsso:
    image: 'suapsso'
    build:
      context: ../dockers/suapsso
    ports:
      - "${APP_EXTERNAL_PORT}:8000"
    env_file:
      - .env
    volumes:
      - '../app/:/app'
    depends_on:
      - db
    command: python3 manage.py runserver 0.0.0.0:8000
