version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5440:5432"
  suapsso:
    image: 'suapsso'
    build:
      context: ../dockers/suapsso
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - '../app/:/app'
    depends_on:
      - db

