version: '3'

services:
  db:
    image: postgres:10.5-alpine
    env_file:
      - .env
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    volumes:
      - "../volumes/pgdata:/var/lib/postgresql/data"
      - "../dockers/db/initdb.d:/docker-entrypoint-initdb.d"

  proxy:
    image: nginx:1.15.5-alpine
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
    volumes:
      - "../dockers/proxy/conf.d:/etc/nginx/conf.d"
    depends_on:
      - acesso
      - authn
      - perfil

  acesso:
    image: 'ifrn/suap-acesso:1.1'
    build:
      context: ../dockers/suap_acesso
    env_file:
      - .env
    volumes:
      - '../apps/suap_acesso:/apps/app'

  authn:
    image: 'ifrn/ege_django_base:1.0'
    env_file:
      - .env
    volumes:
      - '../apps/suap_authn:/apps/app'

  perfil:
    image: 'ifrn/ege_django_base:1.0'
    env_file:
      - .env
    volumes:
      - '../apps/ege_django_theme:/apps/ege_django_theme'
      - '../apps/suap_perfil:/apps/app'
