# Generated by Django 2.1.4 on 2019-02-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ege_acesso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('category', models.CharField(choices=[('Visão', 'Visão'), ('Audição', 'Audição'), ('Outras', 'Outras')], max_length=250, verbose_name='category')),
            ],
            options={
                'verbose_name': 'special need',
                'verbose_name_plural': 'special needs',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='biografy',
            field=models.TextField(blank=True, null=True, verbose_name='biografy'),
        ),
        migrations.AddField(
            model_name='user',
            name='font_size',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='font size'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_biografy_public',
            field=models.TextField(blank=True, null=True, verbose_name='show to all'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_special_needs_public',
            field=models.NullBooleanField(verbose_name='show to all'),
        ),
        migrations.AddField(
            model_name='user',
            name='legends',
            field=models.NullBooleanField(verbose_name='legends'),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_photo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='pending photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='photo_approved at'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_approved_by',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='photo_approved by'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_solicitation_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='photo_solicitation_at'),
        ),
        migrations.AddField(
            model_name='user',
            name='screen_reader',
            field=models.NullBooleanField(verbose_name='screen reader'),
        ),
        migrations.AddField(
            model_name='user',
            name='sign_language',
            field=models.NullBooleanField(verbose_name='sign language'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_skin',
            field=models.CharField(blank=True, choices=[('avadefault', 'AVA padrão'), ('avaalternative', 'AVA alternativo'), ('egedefault', 'EGE padrão'), ('egealternative', 'EGE alternativo'), ('highcontrast', 'Alto contraste'), ('dark', 'Dark'), ('contrast', 'Contraste'), ('golden', 'Dourado'), ('purple', 'Púrpura'), ('navy', 'Marinha'), ('coral', 'Coral')], max_length=250, null=True, verbose_name='theme skin'),
        ),
        migrations.AddField(
            model_name='user',
            name='valid_photo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='valid photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='special_needs',
            field=models.ManyToManyField(to='ege_acesso.SpecialNeed', verbose_name='special needs'),
        ),
    ]
