version: '3'

services:
  db:
    image: postgres
  suapsso:
    image: 'suapsso'
    build:
      context: ./suapsso
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    volumes:
      - '../app/:/app'
    depends_on:
      - db

