# Generated by Django 3.0.3 on 2020-03-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme_skin',
            field=models.CharField(blank=True, choices=[('ava_ead_default', 'AVA padrão'), ('ava_ead_alternative', 'AVA alternativo'), ('suap_ead_default', 'SUAP-EaD padrão'), ('suap_ead_alternative', 'SUAP-EaD alternativo'), ('highcontrast', 'Alto contraste'), ('dark', 'Dark'), ('contrast', 'Contraste'), ('golden', 'Dourado'), ('purple', 'Púrpura'), ('navy', 'Marinha'), ('coral', 'Coral')], max_length=250, null=True, verbose_name='theme skin'),
        ),
    ]
