# Generated by Django 3.0.3 on 2020-03-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0002_auto_20200310_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_needs',
            field=models.ManyToManyField(blank=True, null=True, to='id.SpecialNeed', verbose_name='special needs'),
        ),
    ]
