# Generated by Django 3.0.3 on 2020-03-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0003_auto_20200311_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_needs',
            field=models.ManyToManyField(blank=True, to='id.SpecialNeed', verbose_name='special needs'),
        ),
    ]
